[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 4
via_ir = true
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 0  # Set the number of optimizer runs here

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
