fmt:
	forge fmt
.PHONY: fmt

build:
	forge build --use 0.8.20 --sizes
.PHONY: build

# -vvvv for verbose output
test:
	forge test -vvvv --use 0.8.20
.PHONY: test

install:
	forge install
.PHONY: install
